
% Create output data
outputData = struct(...
    'runSuccessSim', 'true', ...
    ... KINEMATICS
    'time_main', t, ...
    'position', y(:, 1:3), ...
    'velocity', -y(:, 4:6), ...
    'eulerAngles', y(:, 7:9), ...
    'angularVelocity', y(:, 10:12), ...
    'rotor_position', y(:, 13), ...
    'rotor_velocity', y(:, 14), ...
    ... OTHER
    'pos_sec', BLADE.pos_sec, ...
    ... KINEMATICS
    'time_second', sim_data.t, ...
    'height', sim_data.height, ...
    'acceleration', sim_data.a, ...
    'angularAcceleration', sim_data.dw, ...
    ... ROTOR
    'rotor_torque', sim_data.rotor_torque, ...
    'shaft_torque', sim_data.t_shaft, ...
    'rotor_acceleration', sim_data.rotor_acceleration, ...
    ... STALL
    'stall_percentage' , sim_data.stall_percentage, ...    
    ... % FORCES
    'rotorForce', sim_data.F_rotor, ...
    'gravityForce', sim_data.F_g, ...
    'cilinderDragForce', sim_data.F_drag_cilinder, ...
    'totalForce', sim_data.F_total, ...
    ... % ATMOSPHERE MODEL
    'temperature', sim_data.temperature, ...
    'pressure', sim_data.pressure, ...
    'density', sim_data.density, ...
    'dynamicViscosity', sim_data.dynamicVisvosity, ...
    'kinematicViscosity', sim_data.kinecticViscosity, ...
    'soundSpeed', sim_data.soundSpeed, ...
    ... % ADDITIONAL VARIABLES
    'b_time', sim_data.b_time, ...
    'b_df_x', sim_data.b_df_x, ...
    'b_df_y', sim_data.b_df_y, ...
    'b_df_z', sim_data.b_df_z, ...
    'b_dtau_x', sim_data.b_dtau_x, ...
    'b_dtau_y', sim_data.b_dtau_y, ...
    'b_dtau_z', sim_data.b_dtau_z, ...
    'b_v_x', sim_data.b_v_x, ...
    'b_v_y', sim_data.b_v_y, ...
    'b_v_z', sim_data.b_v_z, ...
    'b_ang_v', sim_data.b_ang_v, ...
    'b_total_v', sim_data.b_total_v, ...
    'b_dL', sim_data.b_dL, ...
    'b_dD', sim_data.b_dD, ...
    'b_alpha', sim_data.b_alpha, ...
    'b_theta', sim_data.b_theta, ...
    'b_phi', sim_data.b_phi, ...
    'b_element_state', sim_data.b_element_state, ...
    'b_Ma', sim_data.b_Ma, ...
    'b_Re', sim_data.b_Re, ...
    'b_Cl', sim_data.b_Cl, ...
    'b_Cd', sim_data.b_Cd, ...
    'b_U_T', sim_data.b_U_T, ...
    'b_U_R', sim_data.b_U_R, ...
    'b_U_P', sim_data.b_U_P, ...
    'b_f_prandtl', sim_data.b_f_prandtl, ...
    'b_df_z_prandtl', sim_data.b_df_z_prandtl, ...
    'b_stallAngle', sim_data.b_stallAngle, ...
    'b_stallMode', sim_data.b_stallMode ...
    );


